"""
Generate audio files using OpenAI
To use this script, create .env file and add your API_KEY as follows:
OPENAI_API_KEY=XXXXXX

These four voices were used for 2 males and 1 female

alloy = "alloy" # male
onyx = "onyx" # male
nova = "nova" # female

usage: python generate_openai.py -i "real1.tsv" -o "output" -g "male" -t "fake1.tsv" -v "alloy"
"""
from openai import OpenAI
import os
import pandas as pd
from datasets import Dataset
from dotenv import load_dotenv
import argparse

load_dotenv()


def dataset(path, gender):
    batch = pd.read_csv(path, sep="\t")
    selected_columns = ['path', 'sentence']
    df_subset = batch[selected_columns]
    df_subset['gender'] = gender
    hf_dataset = Dataset.from_pandas(df_subset)
    return hf_dataset

def generate_audio(text, voice, audio_file, output_folder):
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    file_path = os.path.join(output_folder, f"{audio_file}.mp3")

    with client.audio.speech.with_streaming_response.create(model="gpt-4o-mini-tts", voice=voice, input=text) as response:
        response.stream_to_file(file_path)
        
    return file_path


def create_generated_audio(batch, voice, output_dir):
    batch['fake'] = f"fake_{batch['path']}"
    batch['tts'] = "gpt-4o-mini-tts"
    generate_audio(batch['sentence'],  voice, os.path.splitext(batch['fake'])[0], output_dir)
    return batch


if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-i","--input_file", dest="input_file", default=None, help="tsv file inclusing sentence to be generated by tts.")
    parser.add_argument("-o","--output_dir", dest="output_dir", default=None, help="the output dir")
    parser.add_argument("-g","--gender", dest="gender", default=None, help="the output dir")
    parser.add_argument("-t","--tsv_file", dest="tsv_file", default=None, help="the output dir")
    parser.add_argument("-v","--voice", dest="voice", default=None, help="the output dir")

    parser.set_defaults(verbose=False)
    args = parser.parse_args()

    input_file: str = args.input_file
    output_dir: str = args.output_dir
    gender: str = args.gender
    tsv_file:str = args.tsv_file
    voice:str = args.voice

    data = dataset(args.input_file, args.gender)
    df = data.map(lambda batch: create_generated_audio(batch, voice=args.voice, output_dir=args.output_dir))
    df = df.to_pandas()
    df.to_csv(os.path.join(args.output_dir, args.tsv_file), sep="\t", index=False)