"""
Generate audio files using ElevenLabs
To use this script, create .env file and add your ELEVENLABS_API_KEY as follows:
ELEVENLABS_API_KEY=XXXXXX

These four voices were used for 2 males and 2 females

female_1 = "jAAHNNqlbAX9iWjJPEtE"
female_2 = "OfGMGmhShO8iL9jCkXy8"
male_1 = "QRq5hPRAKf5ZhSlTBH6r"
male_2 = "A9ATTqUUQ6GHu0coCz8t"

usage: python generate_elevenlabs.py -i "real1.tsv" -o "output" -g "female" -t "fake1.tsv" -v "jAAHNNqlbAX9iWjJPEtE"
"""

from dotenv import load_dotenv
from elevenlabs import ElevenLabs
import os
import pandas as pd
from datasets import Dataset
import argparse

load_dotenv()

def dataset(path, gender):
    batch = pd.read_csv(path, sep="\t")
    selected_columns = ['path', 'sentence'] 
    df_subset = batch[selected_columns]
    df_subset['gender'] = gender
    hf_dataset = Dataset.from_pandas(df_subset)
    return hf_dataset

def generate_audio(text, voice, audio_file, output_folder):
    client = ElevenLabs(api_key=os.getenv("ELEVENLABS_API_KEY"))
    audio = client.text_to_speech.convert(
        text=text,
        voice_id=voice,
        model_id="eleven_multilingual_v2",
        output_format="mp3_44100_128",
    )

    with open(os.path.join(output_folder, f"{audio_file}.mp3"), "wb") as f:
        for chunk in audio:
            f.write(chunk)

def create_generated_audio(batch, voice, output_dir):
    batch['fake'] = f"fake_{batch['path']}"
    batch['tts'] = "eleven_multilingual_v2"
    generate_audio(batch['sentence'],  voice, os.path.splitext(batch['fake'])[0], output_dir)
    return batch


if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-i","--input_file", dest="input_file", default=None, help="tsv file inclusing sentence to be generated by tts.")
    parser.add_argument("-o","--output_dir", dest="output_dir", default=None, help="the output dir")
    parser.add_argument("-g","--gender", dest="gender", default=None, help="the output dir")
    parser.add_argument("-t","--tsv_file", dest="tsv_file", default=None, help="the output dir")
    parser.add_argument("-v","--voice", dest="voice", default=None, help="the output dir")

    parser.set_defaults(verbose=False)
    args = parser.parse_args()

    input_file: str = args.input_file
    output_dir: str = args.output_dir
    gender: str = args.gender
    tsv_file:str = args.tsv_file
    voice:str = args.voice

    data = dataset(args.input_file, args.gender)
    df = data.map(lambda batch: create_generated_audio(batch, voice=args.voice, output_dir=args.output_dir))
    df = df.to_pandas()
    df.to_csv(os.path.join(args.output_dir, args.tsv_file), sep="\t", index=False)

    


